name = "nuxt-learning-hub"
main = ".output/server/index.mjs"
compatibility_date = "2025-07-15"

[[d1_databases]]
binding = "DB"
database_name = "nuxt-learning-hub"
database_id = "0b71b45a-aa2d-40af-91a7-bb6a60ab96b7"
